#!/bin/bash

# Menampilkan ASCII Art untuk "Blustack"
echo "
  _     _           _             _    
 | |   | |         | |           | |   
 | |__ | |_   _ ___| |_ __ _  ___| | __
 | '_ \| | | | / __| __/ _\` |/ __| |/ /
 | |_) | | |_| \__ \ || (_| | (__|   < 
 |_.__/|_|\__,_|___/\__\__,_|\___|_|\_\
"

# Prompt untuk user (default: root)
read -p "Masukkan nama user untuk menjalankan executor (default: root): " EXECUTOR_USER
EXECUTOR_USER=${EXECUTOR_USER:-root}

# Hentikan & hapus service lama
if systemctl list-units --full -all | grep -q "t3rn-executor.service"; then
    sudo systemctl stop t3rn-executor.service
    sudo systemctl disable t3rn-executor.service
    sudo systemctl daemon-reload
fi

# Hapus file lama
sudo rm -rf /home/$EXECUTOR_USER/t3rn
sudo rm -rf /etc/systemd/system/t3rn-executor.service
sudo rm -rf /etc/t3rn-executor.env

# Prompt Private Key
while [[ -z "$PRIVATE_KEY_LOCAL" ]]; do
    read -sp "Masukkan PRIVATE_KEY_LOCAL (tidak boleh kosong): " PRIVATE_KEY_LOCAL
    echo ""
done

# Prompt Alchemy API
while [[ -z "$APIKEY_ALCHEMY" ]]; do
    read -p "API Key Alchemy (tidak boleh kosong): " APIKEY_ALCHEMY
    echo
done

# Prompt Gas Price
while [[ -z "$GAS_PRICE" ]]; do
    read -p "Gas Price (tidak boleh kosong): " GAS_PRICE
    echo
done

# Variabel direktori dan versi
INSTALL_DIR="/home/$EXECUTOR_USER/t3rn"
SERVICE_FILE="/etc/systemd/system/t3rn-executor.service"
ENV_FILE="/etc/t3rn-executor.env"
EXECUTOR_VERSION="_
